### PR TITLE
Add TRACE and CONNECT methods

### PR DESCRIPTION
**Pull request by roxblnfk**
I propose to expand the list of methods so that we have all RFC-bound methods.
The TRACE and CONNECT methods will not be used in the router, but they can be used in other code (parsers, testing tools).

### CODE REVIEW

**Review by xepozz — APPROVED** [review]

**Review by viktorprogger — APPROVED** [review]

**Comment by samdark** [comment]
I don't think that we should have these two methods in this package.

The package itself is about to be used in applications but these two methods aren't going to be needed there:

## TRACE

It is [to be avoided for security reasons](https://owasp.org/www-community/attacks/Cross_Site_Tracing) and Nginx even have it [hardcoded to disable it](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.c#L1953).

Even if you absolutely want it, the method is about echo-ing request back so it could be implemented with a single `TraceMiddleware` and for that doubtful purpose it's fine to hardcode method name once.

## CONNECT

It is extremely unlikely that someone is going to implement SSL handshake in PHP.

**Review by samdark — CHANGES_REQUESTED** [review]
See comment.

**Comment by thenotsoft** [comment]
I see no reason to add, add only so that there is a complete RFC, but will not be used, why?

**Comment by roxblnfk** [comment]
> I see no reason to add, add only so that there is a complete RFC, but will not be used, why?

We only provide tools. Whether the user will use them is up to the user to decide.
By themselves, such as classes and Method Header are simply directories.
A lot of headers of the Header class are not used and it is not a fact that they will be used.

**Comment by samdark** [comment]
@roxblnfk unlike headers that are likely to be used, these are unlikely to be used at all as I've noted in https://github.com/yiisoft/http/pull/13#issuecomment-686615411

**Comment by cebe** [comment]
what is the purpose of this class? Is anyone going to write `Method::GET` instead of just `'GET'`?

**Comment by samdark** [comment]
Well, yes:

1. You can do "find usages" in IDE.
2. IDE auto-completes.
3. Typos aren't possible. IDE will complain loud.

**Comment by xepozz** [comment]
> Well, yes:
> 
> 1. You can do "find usages" in IDE.
> 2. IDE auto-completes.
> 3. Typos aren't possible. IDE will complain loud.

The second and the third arguments are not valid.
2. IDE can auto-complete with raw text
3. PHPStorm can spell-check

**Comment by samdark** [comment]
Spell checking is not the same as static analysis. Error level is different, precision is very different as well. For example, spell checking will be fine with using `lost` or `most` instead of `post`.

**Comment by xepozz** [comment]
What is the fate of this PR?

**Comment by samdark** [comment]
I think it's not a good idea to merge it since these methods won't be used ever in any PHP-based app.

Let's close it and wait for any real use-case.

**Pull request closed without merging**
